### ISSUE TITLE
뉴스 리더 앱 개발

### ISSUE THREAD

**Issue by choonghyunryu** [bit2r/bitTomato#6]
## Task

- 토마토 뉴스 기사와 원문 URL을 브라우징할 수 있는 Shiny 앱 개발

## Functions

- [ ] 키워드 검색 기능
- [ ] 원문 기사 웹 브라우징 기능
- [ ] 개별 기사의 시각화 기능
    - 워드클라우드
